config/routes.rb
Rails.application.routes.draw do
  root 'login#index'
  post 'login' => 'login#create'
  delete 'logout' => 'login#destroy'
  get 'users' => 'users#index'
  get 'categories' => 'categories#index'
  get 'customers' => 'customers#index'

  resources :users
  resources :categories
  resources :customers
end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
  has_many :customer_category
end

app/models/customer.rb
# Model for customers
class Customer < ActiveRecord::Base
  belongs_to :user
  has_one :customer_category
end

app/models/customer_category.rb
# model for customer category
class Customer_category < ActiveRecord::Base
  has_one :customer
  belongs_to :categorie
end

app/models/user.rb
# Model for users
class User < ActiveRecord::Base
  has_many :customers
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "35x35>" }, default_url: 'user.jpg'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/ 
  has_secure_password
end

app/controllers/application_controller.rb
# main application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to root_path unless current_user
  end
end

app/controllers/categories_controller.rb
# controller for adding and deleting categories
class CategoriesController < ApplicationController
  before_action :require_user
  def index
    #@categories = Categorie.all
    @categories = Categorie.paginate(:page => params[:page], :per_page => 10)
    @categorie = Categorie.new
  end

  def new
    @categorie = Categorie.new
  end

  def create
    @categorie = Categorie.new(categorie_params)

    respond_to do |format|
      if @categorie.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @categorie = Categorie.find(params[:id])
  end

  def update
    respond_to do |format|
      @categorie = Categorie.find(params[:id])
      if @categorie.update(categorie_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @categorie = Categorie.find(params[:id])
    if @categorie.present?
      @categorie.destroy
    end
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_categorie
    @categorie = Categorie.find(params[:id])
  end

  private

  def categorie_params
    params.require(:categorie).permit(:title)
  end
end

app/controllers/customers_controller.rb
# customer controller for creating updating showing and deleting customers
class CustomersController < ApplicationController
  before_action :require_user

  def index
    @customers = Customer.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @customer = Customer.new
    @categories = Categorie.all
  end

  def create
    puts YAML::dump(:customer)
  end
end

app/controllers/login_controller.rb
# login controller creats and destroys session
class LoginController < ApplicationController
  def index
  end

  def create
    @user = User.find_by_email(params[:login][:email])
    if @user && @user.authenticate(params[:login][:password])
      session[:user_id] = @user.id
      redirect_to '/users'
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/test_controller.rb
sjiaidjais
asdasd
sad

app/controllers/users_controller.rb
# user controller gets all the date for views with users
class UsersController < ApplicationController
  before_action :require_user
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :password, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<div class="col-md-12">
  <h4>Edit Category</h4>
  <%= form_for @categorie do |c| %>
    <p>
      <%= c.label :title, 'Category:' %>
      <%= c.text_field :title  %>
      <%= c.submit %>
    </p>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="col-md-12">
  <h4>Categories</h4>
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th  class="col-md-2">ID</th>
          <th  class="col-md-6">Title</th>
          <th  class="col-md-2">Options</th>
        </tr>
       </thead>
       <tbody id="myTable">
        <% @categories.each do |categorie| %>
          <tr>
            <td><%= categorie.id %></td>
            <td><%= categorie.title %></td>
            <td>
              <%= link_to edit_category_path(categorie) do%>
                <i class="fa fa-pencil" style="font-size: 18px"></i>
              <% end %> 
              <%= link_to  categorie, method: :delete, data: { confirm: 'Are you sure?' } do%>
                <i class="fa fa-times" style="font-size: 18px"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
       </tbody>
    </table>   
  </div>
  <div class="col-md-12 text-right">
   <div class="digg_pagination">
    <%= will_paginate @categories %>
   </div>
  </div>
  <%= form_for @categorie do |c| %>
    <p>
      <%= c.label :title, 'Category:' %>
      <%= c.text_field :title  %>
      <%= c.submit %>
    </p>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= form_for @categorie do |c| %>
  <p>
    <%= c.label :title %><br>
    <%= c.text_field :title %>
  </p>

  <p>
    <%= c.submit %>
  </p>
<% end %>

app/views/customers/copy.html.erb
<div class="col-md-12">
  <h4>Customers</h4>
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th  class="col-md-1">ID</th>
          <th  class="col-md-2">Title</th>
          <th  class="col-md-2">Email</th>
          <th  class="col-md-2">Category</th>
          <th  class="col-md-1">Options</th>
        </tr>
       </thead>
       <tbody>
          <tr>
            <td>1</td>
            <td>Test 1</td>
            <td>Test 1</td>
            <td>Test 1</td>
            <td>Test 1</td>
          </tr>
       </tbody>
    </table>   
  </div>
  <div class="col-md-12 text-right">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/customers/index.html.erb
<div class="col-md-12">
  <h4>Customers</h4>
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th  class="col-md-1">ID</th>
          <th  class="col-md-2">Title</th>
          <th  class="col-md-2">Email</th>
          <th  class="col-md-2">Category</th>
          <th  class="col-md-1">Options</th>
        </tr>
       </thead>
       <tbody>
          <tr>
            <td>1</td>
            <td>Test 1</td>
            <td>Test 1</td>
            <td>Test 1</td>
            <td>Test 1</td>
          </tr>
       </tbody>
    </table>   
  </div>
  <div class="col-md-12 text-right">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/customers/new.html.erb
<%= form_for @customer do |c| %>

<table class="table table-user-information">
  <tbody>
    <tr>
      <td><%= c.label :title, 'Title:' %></td>
      <td><%= c.text_field :title %></td>
    </tr>
    <tr>
      <td><%= c.label :email, 'Email:' %></td>
      <td><%= c.text_field :email %></td>
    </tr>
    <tr>
      <td>Category:</td>
      <td>
        <select name="category_id">
          <%= @categories.each do |category| %>
            <option value="<%= category.id %>"><%= category.title %></option>
          <% end %>
        </select>
      </td>
    </tr>
   </tbody>
 </table>
      <%= c.submit "Submit", class: "btn btn-primary" %>
 </div>
 <% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <p>&copy; Company 2015</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
  <% unless current_page?(root_path) %>
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  <% end %>
    <a class="navbar-brand" href="#">CustomerApp</a>
      <% unless current_page?(root_path) %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav" style="float: right">
            <li>  
              <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
                Customers
              </a>
              <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                <li><%= link_to "All Customers", '/customers' %> </li>
                <li><a href="#">New Customer</a></li>
                <li><%= link_to "Categories", '/categories' %> </li>
              </ul>
            </li>
            <li>  
              <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
                Users
              </a>
              <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                <li><%= link_to "All Users", '/users' %> </li>
                <li><%= link_to "New User", '/users/new' %> </li>
              </ul>
            </li>
            <li><%= link_to "Settings", "/path3"  %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        </div>
      <% end %>
    </div>

</header>

app/views/layouts/_sidebar.html.erb
         <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
           <div class="sidebar-background">
            <ul class="nav nav-sidebar"> 
              <li class="active"><a href="#">Overview</a></li>
              <li><a href="#">Users</a></li>
              <li><a href="#">Customers</a></li>
              <li><a href="#">Categories</a></li>
              <li><a href="#">Payments</a></li>
              <li><a href="#">Settings</a></li>
            </ul>
           </div>
        </div><!--/span-->
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CustomerApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/header' %>
       
    <div class="container">
      <div class="row">

        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->
      <%= render 'layouts/footer' %>
    </div> <!-- /container -->

  </body>
</html>

app/views/login/index.html.erb
<div class="container">
    <div class="row vertical-offset-100">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please sign in</h3>
          </div>
          <div class="panel-body">
            <%= form_for(:login, url: login_path) do |f| %> 
              <fieldset>
                <div class="form-group">
                   <%= f.email_field :email, :placeholder => "Email", class: "form-control"  %> 
                </div>
                <div class="form-group">
                   <%= f.password_field :password, :placeholder => "Password", class: "form-control" %> 
                </div>
                <div class="checkbox">
                  <label>
                    <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                  </label>
                </div>
                  <%= f.submit "Login", class: "btn btn-lg btn-success btn-block" %>
              </fieldset>
           <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |u| %>
<div class="col-md-3 col-md-offset-1">
    <% if @user.avatar.url %>
      <%= image_tag @user.avatar.url, :class => "img-circle img-responsive" %>
    <% else %>
      <%= image_tag "user.jpg", :class => "img-circle img-responsive"  %>
    <% end %>
  <p>
    <%= u.file_field :avatar %>
  </p>
</div>
<div class="col-md-6 col-md-offset-2" >
<table class="table table-user-information">
  <tbody>
    <tr>
      <td><%= u.label :name, 'Name:' %></td>
      <td><%= u.text_field :name %></td>
    </tr>
    <tr>
      <td><%= u.label :surname, 'Surname:' %></td>
      <td><%= u.text_field :surname %></td>
    </tr>
    <tr>
      <td><%= u.label :email, 'Email:' %></td>
      <td><%= u.text_field :email %></td>
    </tr>
    <tr>
      <td><%= u.label :password, 'Password:' %></td>
      <td><%= u.password_field :password %></td>
    </tr>
    <tr>
      <td><%= u.label :password_confirmation, "Password confirmation:" %></td>
      <td><%= u.password_field :password_confirmation %></td>
    </tr>
   </tbody>
 </table>
      <%= u.submit "Submit", class: "btn btn-primary" %>
 </div>
 <% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="col-md-12">
  <h4>Users table</h4>
<div class="table-responsive">
  <table class="table table-bordered table-hover" >
    <thead>
      <tr class="filters">
        <th>ID</th>
        <th>Avatar</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Email</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <% if user.avatar.file? %>
            <td><%= image_tag user.avatar.url(:thumb) %></td>
          <% else %>
            <td><%= image_tag "user_thumb.jpg" %></td>
          <% end %>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to user do%> 
              <i class="fa fa-search" style="font-size: 18px"></i>
            <% end %>
            <%= link_to edit_user_path(user) do%>
              <i class="fa fa-pencil" style="font-size: 18px"></i>
            <% end %> 
            <%= link_to  user, method: :delete, data: { confirm: 'Are you sure?' } do%>
              <i class="fa fa-times" style="font-size: 18px"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
     </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<h1>Add new User</h1>
<%= render 'form' %>
 

app/views/users/show.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"> <%= @user.name %> <%= @user.surname %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3 " align="center"> 
            <%= image_tag @user.avatar.url, :class => "img-circle img-responsive"%>
          </div>
            <div class=" col-md-9 col-lg-9 "> 
              <table class="table table-user-information">
                <tbody>
                  <tr>
                    <td>First name:</td>
                    <td><%= @user.name %></td>
                  </tr>
                  <tr>
                    <td>Last name:</td>
                    <td><%= @user.surname %></td>
                  </tr>
                  <tr>
                    <td>Email</td>
                    <td><%= @user.email %></td>
                  </tr>
                  <tr>
                    <td>Status</td>
                    <td>Admin</td>
                  </tr>
                </tbody>
              </table>
              <a href="#" class="btn btn-primary">Customers</a>
              <a href="#" class="btn btn-primary">Applications</a>
            </div>
          </div>
        </div>
        <div class="panel-footer" style="height:55px">
          <span class="pull-right">
             <%= link_to edit_user_path(@user) do%>
              <i class="fa fa-pencil" style="font-size: 25px"></i>
            <% end %> 
            <%= link_to  @user, method: :delete, data: { confirm: 'Are you sure?' } do%>
              <i class="fa fa-times" style="font-size: 25px"></i>
            <% end %>
          </span>
        </div>
    </div>
  </div>
</div>